image: node:lts

cache:
  paths:
    - node_modules/

stages:
  - lint
  - deploy

lint_app:
  stage: lint
  script:
    - echo "Run linter"
    - npm ci
    - npm run lint

deploy_app:
  stage: deploy
  needs: []
  script:
    - echo "Build and deploy the app"
    - npm ci
    - npm install -g firebase-tools @ionic/cli
    - npm run build
    - firebase deploy
  only:
    - main
