image: node:lts

cache:
  paths:
    - node_modules/

stages:
  - lint
  - build
  - deploy

lint_app:
  stage: lint
  script:
    - echo "Run linter"
    - npm install
    - npm run lint

build_app:
  stage: build
  script:
    - echo "Run build"
    - npm install
    - npm i @ionic/cli
    - npm run build

deploy_app:
  stage: deploy
  needs: [build_app]
  script:
    - echo "Run deployment"
    - npm i firebase-tools
    - firebase deploy:ci
  only:
    - main
